### ISSUE TITLE
Brightness not working on v6 bridge

### ISSUE THREAD

**Issue by exdirectory** [mookfist/mookfist-lled-controller#9]
python lled.py brightness 1 --group=1 --bridge-ip=192.168.1.81 --bridge-version=6

Command fails, have tried debugging code but it is a bit beyond my skill set. Output and traceback...

0:00:00 [INFO    ] Welcome to the Mookfist LimitlessLED Controller
0:00:00.000983 [INFO    ] --- Bridge Details
0:00:00.001984 [INFO    ] Version: 6
0:00:00.001984 [INFO    ] IP: 192.168.1.81
0:00:00.002985 [INFO    ] Port: 5987
0:00:00.005987 [INFO    ] Setting brightness to 1%
Traceback (most recent call last):
  File "lled.py", line 54, in <module>
    main()
  File "lled.py", line 48, in main
    m.run()
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\cli.py", line 245, in run
    self.route_action()
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\cli.py", line 181, in route_action
    self.action_brightness()
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\cli.py", line 144, in action_brightness
    self.bridge.brightness(self.arguments['--group'])
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\bridge.py", line 211, in brightness
    self._send(g.brightness(brightness))
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\bridges\ver6.py", line 188, in _send
    cmd[21] = cmd.checksum()
  File "c:\Python3\lib\site-packages\mookfist_lled_controller\bridges\ver6.py", line 40, in checksum
    return sum(bytearray(self._cmd[10:21])) & 0xff
TypeError: an integer is required

**Comment by mookfist** [comment]
thank you for the bug report. I've identified the issue.

**Comment by mookfist** [comment]
I fixed the issue and will push v0.1.2 today to pypi after some testing.

**Comment by exdirectory** [comment]
Thanks

**Comment by mookfist** [comment]
There are some build issues. I will attempt to push 0.1.2 tomorrow to pypi.

**Comment by mookfist** [comment]
or you can can try checking out the develop branch yourself if you can't wait much longer:

```
$ git clone https://github.com/mookfist/mookfist-lled-controller.git
$ git checkout develop
$ python setup.py install

```
for example

**Comment by mookfist** [comment]
0.1.2 is now published to pypi with this issue resolved.

Thank you for the bug report and your patience.
